---
name: Employee Manager
version: "1.0.11"
slug: employee_manager
description: System zarzÄ…dzania pracownikami
url: https://github.com/k4y0W/HA-addon
startup: application
boot: auto
init: false
arch:
  - aarch64
  - amd64
options: {}
schema: {}
