name: Employee Manager
version: "1.1.7"
slug: employee_manager
description: System zarzÄ…dzania pracownikami
url: https://github.com/k4y0W/HA-addon
startup: application
boot: auto
init: false
homeassistant_api: true
map:
  - config:rw
arch:
  - aarch64
  - amd64
ingress: true
panel_icon: mdi:account-group
environment:
  PYTHON_LOG_LEVEL: info
options:
  employees: []
schema:
  employees:
    - name: str
      typ_pomiaru: list(Temperatura|Wilgotnosc|Cisnienie)
      threshold_value: float
