name: Employee Manager
version: "1.1.3"
slug: employee_manager
description: System zarzÄ…dzania pracownikami
url: https://github.com/k4y0W/HA-addon
startup: application
boot: auto
init: false
homeassistant_api: true
map:
  - config:rw
arch:
  - aarch64
  - amd64
options:
  employees: []
schema:
  employees:
    - name: str
      power_sensor: str
      motion_sensor: str
      threshold_watts: float
