name: Employee Manager
version: "1.2.84"
slug: employee_manager_v2
description: System zarzÄ…dzania pracownikami
url: https://github.com/k4y0W/HA-addon
startup: application
boot: auto
init: false
homeassistant_api: true
ingress: true
panel_icon: mdi:account-group
map:
  - config:rw
arch:
  - aarch64
  - amd64
options: {}
schema: {}
