---
name: Deploy Simple

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        arch: [aarch64, amd64]

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Zaloguj do GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: k4y0w
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Konfiguracja QEMU (do budowania na różne procki)
        uses: docker/setup-qemu-action@v3

      - name: Konfiguracja Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Buduj i Wysyłaj
        uses: docker/build-push-action@v5
        with:
          context: ./example
          file: ./example/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ghcr.io/k4y0w/ha-addon/example-${{ matrix.arch }}:latest
            ghcr.io/k4y0w/ha-addon/example-${{ matrix.arch }}:${{ github.sha }}
